stages:
  - image
  - helm

variables:
  # kaniko options
  DOCKERFILE: "./Dockerfile"
  DOCKLE_OPTIONS: "--ignore CIS-DI-0001"
  HADOLINT_IGNORE: "--ignore DL3018 --ignore DL3026"
  # helm-chart options
  CHART_DIRS: install/kubernetes

kaniko:
  stage: image
  needs: []
  trigger:
    include:
      - project: cloudnative/gitlab/gitlabci/kaniko-image-ci
        ref: v1.X
        file: .kaniko.gitlab-ci.yml
    strategy: depend

helm:
  stage: helm
  needs: []
  trigger:
    include:
      - project: cloudnative/gitlab/gitlabci/helm-chart
        ref: v4.x
        file: .helm.gitlab-ci.yml
    strategy: depend
