include:
  - project: cloudnative/gitlab/gitlabci/kaniko-image-ci
    ref: v1.X
    file: .kaniko.gitlab-ci.yml

variables:
  IMAGE_REPOSITORY: artifactory.cloud.statcan.ca/cwmd-cns-docker-local/cidr-allocator
  KANIKO_OPTIONS: "--build-arg IMAGE_REPOSITORY=artifactory.cloud.statcan.ca/docker"
  DOCKERFILE: "./Dockerfile"
  DOCKLE_OPTIONS: "--ignore CIS-DI-0001"
  HADOLINT_IGNORE: "--ignore DL3018 --ignore DL3026"

stages:
  - version
  - build
  - scan
  - push
  - tag

trivy:
  allow_failure: true
