# permissions for end users to view nodecidrallocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nodecidrallocation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cidr-allocator
    app.kubernetes.io/part-of: cidr-allocator
    app.kubernetes.io/managed-by: kustomize
  name: nodecidrallocation-viewer-role
rules:
- apiGroups:
  - networking.statcan.gc.ca
  resources:
  - nodecidrallocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.statcan.gc.ca
  resources:
  - nodecidrallocations/status
  verbs:
  - get
