---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.statcan.gc.ca
  resources:
  - nodecidrallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.statcan.gc.ca
  resources:
  - nodecidrallocations/finalizers
  verbs:
  - update
- apiGroups:
  - networking.statcan.gc.ca
  resources:
  - nodecidrallocations/status
  verbs:
  - get
  - patch
  - update
